### ISSUE TITLE
not working with my theme.

### ISSUE THREAD

**Issue by mxmkmarquette** [elcobvg/wordpress-opcache#2]
the minute i put the drop in error all over the place...

`
Warning: Invalid argument supplied for foreach() in /srv/users/serverpilot/apps/madmax/public/wp-content/plugins/woocommerce/includes/wc-webhook-functions.php on line 106

Warning: array_merge(): Argument #2 is not an array in /srv/users/serverpilot/apps/madmax/public/wp-content/themes/bimber/includes/theme-setup.php on line 174

Warning: array_filter() expects parameter 1 to be array, null given in /srv/users/serverpilot/apps/madmax/public/wp-content/plugins/woocommerce/includes/wc-attribute-functions.php on line 62

Fatal error: Uncaught Error: Call to a member function have_posts() on null in /srv/users/serverpilot/apps/madmax/public/wp-content/themes/bimber/includes/front/post.php:774 Stack trace: #0 /srv/users/serverpilot/apps/madmax/public/wp-content/themes/bimber/includes/front/post.php(551): bimber_get_global_featured_posts_ids() #1 /srv/users/serverpilot/apps/madmax/public/wp-content/themes/bimber/includes/front/home.php(109): bimber_get_featured_posts_ids(Array) #2 /srv/users/serverpilot/apps/madmax/public/wp-content/themes/bimber/includes/front/home.php(126): bimber_get_home_featured_posts_ids() #3 /srv/users/serverpilot/apps/madmax/public/wp-includes/class-wp-hook.php(286): bimber_home_exclude_featured(Object(WP_Query)) #4 /srv/users/serverpilot/apps/madmax/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /srv/users/serverpilot/apps/madmax/public/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #6 /srv/users/serverpilot/apps/madmax/public/wp-includes/class-wp-query.php(1634): do_action in /srv/users/serverpilot/apps/madmax/public/wp-content/themes/bimber/includes/front/post.php on line 774
`
would be real nice to get it working cause i really love this idea.

**Comment by mxmkmarquette** [comment]
i'm on nginx, with zend opcache, php7.2

**Comment by elcobvg** [comment]
Yeah I'm aware of this problem. Unfortunately at the moment I have no time to look into it, I'm sorry...

**Comment by mxmkmarquette** [comment]
no problemo my friend, just reporting cause i was finding this solution more pratical than some other around.

**Comment by mxmkmarquette** [comment]
but thank you for you drop in gonna retake a look time to time :)

**Comment by mxmkmarquette** [comment]
will you look at it now? can give you access?

**Comment by bueltge** [comment]
I see no error from the Dropin, from the opcache solution. The warning messages are always topics from WooCommerce and the theme. So you should deactivate the warning message in the production stage and fix on the Theme.
